# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5b10dc7895dacdcd368268592d02826121ea7b93ac03548755d81631360c1644a43eb066c8fde6bfecc3c9dc136aebd29a5debbf1f3a56d34d271411308643

test:
  secret_key_base: 90c3a7a8b9f959b847fdb1dfb35e926c649773cdb15a3726588b886c9a6a445f402d6b3c5b319b4352d7dc924587d59c64a115325e4ba52f18b1f47a3aedf05b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
